### ISSUE TITLE
Potential Bias in the 2D CNN

### ISSUE THREAD

**Issue by emdupre** [Jean-PhilippeTremblay/deep-mriqc#1]
* As currently implemented, the 2D CNN may have a potential bias source. Because training and testing sets are derived after slices are generated and shuffled, the same participants can appear in both the training and testing sets.
* We did recognize this issue at the hackathon, and this was partially what motivated our move to a 3D CNN (s.t., reported accuracy estimates are for the 3D CNN). However, we did not fix this issue in the existing 2D CNN implementation. 

__Attempts to move forward with this approach should split participants into training and testing before generating slices!__

**Comment by sulantha2006** [comment]
Actually this is fixed in the 2d version. The -gen_portion method is used to make sure that subjects are not mixed between training and testing. However, slicing can misrepresent good slices as bad if they are from a bad MRI to start with.
